[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/healthz"
healthcheckTimeout = 300
healthcheckInterval = 15
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[deploy.envs]
NODE_ENV = "production"