[build]
   builder = "NIXPACKS"
   buildCommand = "npm run build"

[deploy]
   startCommand = "npm run start"
   healthcheckPath = "/healthz"
   healthcheckTimeout = 300
   restartPolicyType = "on_failure"
   restartPolicyMaxRetries = 10